### ISSUE TITLE
develop-next - fatal error - clicking category in front end

### ISSUE THREAD

**Issue by gmt-it** [osTicket/osTicket-1.8#1654]
Fatal error: Uncaught exception 'InconsistentModelException' with message 'Unable to prepare query: SELECT A1.`faq_id`, A1.`category_id`, A1.`ispublished`, A1.`question`, A1.`answer`, A1.`keywords`, A1.`notes`, A1.`views`, A1.`score`, A1.`created`, A1.`updated`, COUNT(A1.`attachments`) AS `has_attachments`, A2.`category_id`, A2.`ispublic`, A2.`name`, A2.`description`, A2.`notes`, A2.`created`, A2.`updated` FROM `ost_faq` A1 JOIN `ost_faq_category` A2 ON (A1.`category_id` = A2.`category_id`) WHERE A2.`category_id` = ? AND NOT A1.`ispublished` = ? GROUP BY A1.faq_id ORDER BY A1.`ispublished` DESC, A1.`question` ASC' in /var/www/develop-next/include/class.orm.php:2082 Stack trace: #0 /var/www/develop-next/include/class.orm.php(2076): MysqlExecutor->execute() #1 /var/www/develop-next/include/class.orm.php(2161): MysqlExecutor->_prepare() #2 /var/www/develop-next/include/class.orm.php(1138): MysqlExecutor->getRow() #3 /var/www/develop-next/include/class.orm.php(979): ModelInstanceManager->fillTo(0) #4 /var/www/develop-next/in in /var/www/develop-next/include/class.orm.php on line 2082

![error_001](https://cloud.githubusercontent.com/assets/10116166/5617485/a784e824-950f-11e4-8c32-2995e0e46668.jpg)
![error_002](https://cloud.githubusercontent.com/assets/10116166/5617488/aea46a9e-950f-11e4-870a-1bb23c64080f.jpg)

**Comment by gmt-it** [comment]
Worksnow, too! ;-)
