### ISSUE TITLE
1.10DPR Upgrade issue

### ISSUE THREAD

**Issue by fgn-git-hub** [osTicket/osTicket-1.8#2078]
I try to install the upgrade, for some reason it worked the first time but I got problems. So I replaced the DB and the files. But now, every time I try the upgrade I get this: 

[CREATE TABLE `ost_translation` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `object_hash` char(16) CHARACTER SET ascii DEFAULT NULL, `type` enum('phrase', 'article', 'override') DEFAULT NULL, `flags` int(10) unsigned NOT NULL DEFAULT '0', `revision` int(11) unsigned DEFAULT NULL, `agent_id` int(10) unsigned NOT NULL DEFAULT '0', `lang` varchar(16) NOT NULL DEFAULT '', `text` mediumtext NOT NULL, `source_text` text, `updated` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), KEY `type` (`type`, `lang`), KEY `object_hash` (`object_hash`) ) DEFAULT CHARSET=utf8] Table '`osTicket`.`ost_translation`' already exists

But the table doesn't exist. 

And this Error repeatedly: 

DB Error #1146

[SELECT A1.* FROM `ost_translation` A1 WHERE (A1.`lang` = ? AND A1.`type` = ?)] Table 'osTicket.ost_translation' doesn't exist

---- Backtrace ----
#0 (root)/include/mysqli.php(318): osTicket->logDBError('DB Error #1146', '[SELECT A1.* FR...')
#1 (root)/include/class.orm.php(2296): db_prepare('SELECT A1.* FRO...')
#2 (root)/include/class.orm.php(2290): MySqlExecutor->execute()
#3 (root)/include/class.orm.php(2366): MySqlExecutor->_prepare()
#4 (root)/include/class.orm.php(1325): MySqlExecutor->getArray()
#5 (root)/include/class.orm.php(1151): ModelInstanceManager->fillTo(0)
#6 (root)/include/class.translation.php(899): ResultSet->valid()
#7 (root)/include/class.translation.php(920): CustomDataTranslation::getTranslation('en_US')
#8 (root)/include/class.list.php(329): CustomDataTranslation::translate('37eec2fe8f75003...')
#9 (root)/include/class.list.php(195): DynamicList->getLocal('name_plural')
#10 (root)/include/class.list.php(450): DynamicList->getPluralName()
#11 [internal function]: DynamicList::getSelections()
#12 (root)/include/class.forms.php(366): call_user_func(Array)
#13 (root)/include/class.forms.php(374): FormField::allTypes()
#14 (root)/include/class.forms.php(740): FormField::getFieldType('text')
#15 [internal function]: FormField->getImpl(Object(DynamicFormField))
#16 (root)/include/class.dynamic_forms.php(627): call_user_func_array(Array, Array)
#17 (root)/include/class.dynamic_forms.php(1319): DynamicFormField->__call('getImpl', Array)
#18 (root)/include/class.dynamic_forms.php(1319): DynamicFormField->getImpl(Object(DynamicFormField))
#19 (root)/include/class.dynamic_forms.php(960): DynamicFormEntryAnswer->getField()
#20 (root)/include/class.company.php(71): DynamicFormEntry->getAnswer('name')
#21 (root)/include/staff/footer.inc.php(5): Company->__toString()
#22 (root)/scp/upgrade.php(88): require('/var/www/localh...')
#23 (root)/scp/staff.inc.php(117): require('/var/www/localh...')
#24 (root)/scp/admin.inc.php(16): require('/var/www/localh...')
#25 (root)/scp/upgrade.php(16): require_once('/var/www/localh...')
#26 (root)/scp/staff.inc.php(117): require('/var/www/localh...')
#27 (root)/scp/autocron.php(18): require('/var/www/localh...')
#28 {main}

That makes no sense, first it comments that the table exists and can't be created and afterwards it's missing?

Another question is, is the LDAP plugin working with that prerelease?
The first time it worked, I just got a blank page after logging in with a ldap user.

**Comment by Chefkeks** [comment]
Are you aware of the fact that a developer preview release should only be tested by doing a clean installation and not an upgrade of an existing installation? And since it's a preview release it shouldn't be used in productive environments either!

**Comment by fgn-git-hub** [comment]
I'm aware that's a preview release, and I tried it on a testing envirment, which does consist of an working production environment. So I tried an upgrade to keep the test data, as far as possible. Do you want to tell me that upgradeing is not possible with a preview?

**Comment by Chefkeks** [comment]
Yes, exactly that's what I want to tell you ;)

**Comment by fgn-git-hub** [comment]
Ok, than I take my question back, and try it without updating. But what I really wanted to test was a version with content which is not working without updating. I guess I have to wait for another version than. 

Thank you

**Comment by greezybacon** [comment]
@fgn-git-hub thanks for the report. Part of the goal of the preview period is to stabilize the upgrade. I'll look into the issue

**Comment by mkaatman** [comment]
This is happening for a 1.9.15 to 1.10 production release as well.

**Comment by fgn-git-hub** [comment]
I still get the same issue with the latest stable, so how do I fix it?

**Comment by fgn-git-hub** [comment]
The strange thing is, that I can't delete the table and recreate it, cause it's not existing, but when I try to create it, I get the feedback it "does" exist already. So what's to do about it?

**Comment by ntozier** [comment]
Did you upgrade your language pack(s)?

**Comment by fgn-git-hub** [comment]
Which one. If I use english I don't need to install any. 
So no, I did not. Do I have to?

**Comment by ntozier** [comment]
Well the queries are about the ost_translate table which I'm pretty sure has to do with translations... so if you upgraded and didn't upgrade the language packs it could do wonky things.  Or if you made a copy of english and installed that and didn't upgrade that, or if you deleted a language pack with out de-selecting it in the UI it might also cause an issue so I was thinking that maybe one of those things were causing the problem.

**Comment by fgn-git-hub** [comment]
Makes sense in general, but what do I need to upgrade or to install to get it fixed?

**Comment by m-a-v** [comment]
I have the same issue:

[SELECT A1.* FROM ost_translation A1 WHERE (A1.lang = ? AND A1.type = ?)] Table 'osTicket.ost_translation' doesn't exist

I am upgrading from v1.9.7 to v1.10.

**Comment by RikkiMasters** [comment]
@m-a-v Had the same issue. Turned out my database user didn't have enough permissions. Used root and worked fine.
