### ISSUE TITLE
dpr: PHP Fatal error:  Uncaught exception 'OrmException'

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#2081]
When open scp/tasks.php

PHP Fatal error:  Uncaught exception 'OrmException' with message 'Model `Task` does not have a relation called `status`' in /xxx/next/include/class.orm.php:1547\nStack trace:\n#0 /xxx/next/include/class.orm.php(1559): SqlCompiler->{closure}('status', Array, 'Task')\n#1 /xxx/next/include/class.orm.php(1683): SqlCompiler->getField('status__state__...', 'Task')\n#2 /xxx/next/include/class.orm.php(1711): SqlCompiler->compileQ(Object(Q), 'Task')\n#3 /xxx/next/include/class.orm.php(1967): SqlCompiler->compileConstraints(Array, 'Task')\n#4 /xxx/next/include/class.orm.php(1990): MySqlCompiler->getWhereHavingClause(Object(QuerySet))\n#5 /xxx/next/include/class.orm.php(961): MySqlCompiler->compileCount(Object(QuerySet))\n#6 /xxx/next/scp/tasks.php(134): QuerySet->count()\n#7 {main}\n  thrown in /xxx/next/include/class.orm.php on line 1547, referer: https://xxx/scp/users.php

PHP Fatal error:  Uncaught exception 'OrmException' with message 'Model `Task` does not have a relation called `status`' in /xxx/next/include/class.orm.php:1547\nStack trace:\n#0 /xxx/next/include/class.orm.php(1559): SqlCompiler->{closure}('status', Array, 'Task')\n#1 /xxx/next/include/class.orm.php(1683): SqlCompiler->getField('status__state__...', 'Task')\n#2 /xxx/next/include/class.orm.php(1711): SqlCompiler->compileQ(Object(Q), 'Task')\n#3 /xxx/next/include/class.orm.php(1967): SqlCompiler->compileConstraints(Array, 'Task')\n#4 /xxx/next/include/class.orm.php(1990): MySqlCompiler->getWhereHavingClause(Object(QuerySet))\n#5 /xxx/next/include/class.orm.php(961): MySqlCompiler->compileCount(Object(QuerySet))\n#6 /xxx/next/scp/tasks.php(134): QuerySet->count()\n#7 {main}\n  thrown in /xxx/next/include/class.orm.php on line 1547, referer: https://xxx/scp/tasks.php

**Comment by infectormp** [comment]
fixed in last branch
