### ISSUE TITLE
dpr: KB related bugs

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#2101]
* FAQ category page not have buttons: Make public, Make internal, Delete
* In created FAQ buttons Print and Edit FAQ doesn't work.
* [Delete FAQ] button delete FAQ without confirmation. (may be not a bug)
* When add new FAQ - GET https://xxx/css/jquery.multiselect.css [404 Not Found]
* When try search FAQ by Helptopic
```
PHP Fatal error:  Uncaught exception 'InconsistentMode
lException' with message 'Unable to prepare query:  
SELECT A1.`faq_id`, A1.`category_id`, A1.`ispublished`,
 A1.`question`, A1.`answer`, A1.`keywords`, A1.`no
tes`, A1.`views`, A1.`score`, A1.`created`, A1.`updated`,
 COUNT(A3.`object_id`) AS `attachment_count`, COUNT(A4.`faq_id`)
 AS `topic_count`, A2.`category_id`,
 A2.`ispublic`, A2.`name`, A2.`description`, A2.`notes`,
 A2.`created`, A2.`updated` FROM `ost_faq` A1 JOIN `ost_faq_category`
 A2 ON (A1.`category_id` = A2.`c
ategory_id`) LEFT JOIN `ost_attachment` A3 ON (A3.`type`
 = ? AND A1.`faq_id` = A3.`object_id`) LEFT JOIN `ost_faq_topic`
 A4 ON (A1.`faq_id` = A4.`faq_id`) WH
ERE A1.`topic_id` = ? GROUP BY A1.faq_id ORDER BY A1.`question`
 ASC' in /xxx/include/class.orm.php:2297\nStack trace:\n#0 /xxx
 /include/class.orm.php(2290): MySqlExecutor->execute()\n#1 /xxx
 /include/class.orm.php(2384): MySqlExecutor->_prepare()\n#2 /xxx
 /include/class.orm.php(1325): MySqlExecutor->ge in /xxx/include
 /class.orm.php on line 2297, referer: https://xxx/scp/kb.php
```
```
[SELECT A1.`faq_id`, A1.`category_id`, A1.`ispublished`, A1.`question`,
 A1.`answer`, A1.`keywords`, A1.`notes`, A1.`views`, A1.`score`, 
A1.`created`, A1.`updated`, COUNT(A3.`object_id`) AS `attachment_count`, 
COUNT(A4.`faq_id`) AS `topic_count`, A2.`category_id`, A2.`ispublic`, 
A2.`name`, A2.`description`, A2.`notes`, A2.`created`, A2.`updated` 
FROM `ost_faq` A1 JOIN `ost_faq_category` A2 ON (A1.`category_id` 
= A2.`category_id`) LEFT JOIN `ost_attachment` A3 ON (A3.`type` = ? 
AND A1.`faq_id` = A3.`object_id`) LEFT JOIN `ost_faq_topic` A4 ON 
(A1.`faq_id` = A4.`faq_id`) WHERE A1.`topic_id` = ? GROUP BY A1.faq_id
 ORDER BY A1.`question` ASC]

Unknown column 'A1.topic_id' in 'where clause'

---- Backtrace ----
#0 (root)/include/mysqli.php(318): osTicket->logDBError('DB Error #1054', '[SELECT A1.`faq...')
#1 (root)/include/class.orm.php(2296): db_prepare('SELECT A1.`faq_...')
#2 (root)/include/class.orm.php(2290): MySqlExecutor->execute()
#3 (root)/include/class.orm.php(2384): MySqlExecutor->_prepare()
#4 (root)/include/class.orm.php(1325): MySqlExecutor->getRow()
#5 (root)/include/class.orm.php(1161): ModelInstanceManager->fillTo(0)
#6 (root)/include/class.orm.php(1037): ResultSet->offsetGet(0)
#7 (root)/include/class.orm.php(983): QuerySet->offsetGet(0)
#8 (root)/include/staff/faq-categories.inc.php(78): QuerySet->exists(true)
#9 (root)/scp/kb.php(31): require_once('/...')
#10 {main}
```

**Comment by greezybacon** [comment]
> When try search FAQ by Helptopic

This is fixed in #2056 as of 22cd42d

> When add new FAQ - GET https://xxx/css/jquery.multiselect.css [404 Not Found]

This is fixed in #2056 as of 6ab5840

> In created FAQ buttons Print and Edit FAQ doesn't work.

I can't confirm this

**Comment by infectormp** [comment]
> In created FAQ buttons Print and Edit FAQ doesn't work.

my fault. not work only in FF DE.

**Comment by mfelber** [comment]
I can confirm that the Edit and Print Button in a faq doesn't work for example in Firefox 38.0.1.

**Comment by infectormp** [comment]
> When try search FAQ by Helptopic
> When add new FAQ - GET https://xxx/css/jquery.multiselect.css [404 Not Found]

fixed

**Comment by mfelber** [comment]
@greezybacon With the actual issue/next-stabilize branch, the "Edit" and "Print" Buttons in a faq are working fine with Firefox 38.0.1.

**Comment by infectormp** [comment]
> In created FAQ buttons Print and Edit FAQ doesn't work.

fixed in last branch

**Comment by infectormp** [comment]
> FAQ category page not have buttons: Make public, Make internal, Delete

bug still here

**Comment by infectormp** [comment]
In RC1 fixed
