### ISSUE TITLE
ost_ticket__cdata table issue

### ISSUE THREAD

**Issue by gtulga** [osTicket/osTicket-1.8#2138]
I still have this problem on v1.9.8.1. I received email:
```
[SELECT ticket.ticket_id,tlock.lock_id,ticket.`number`,ticket.dept_id,ticket.staff_id,ticket.team_id  ,user.name ,email.address as email, dept.dept_name, status.state  ,status.name as status,ticket.source,ticket.isoverdue,ticket.isanswered,ticket.created  ,IF(ticket.duedate IS NULL,IF(sla.id IS NULL, NULL, DATE_ADD(ticket.created, INTERVAL sla.grace_period HOUR)), ticket.duedate) as duedate  ,CAST(GREATEST(IFNULL(ticket.lastmessage, 0), IFNULL(ticket.closed, 0), IFNULL(ticket.reopened, 0), ticket.created) as datetime) as effective_date  ,ticket.created as ticket_created, CONCAT_WS(" ", staff.firstname, staff.lastname) as staff, team.name as team  ,IF(staff.staff_id IS NULL,team.name,CONCAT_WS(" ", staff.lastname, staff.firstname)) as assigned  ,IF(ptopic.topic_pid IS NULL, topic.topic, CONCAT_WS(" / ", ptopic.topic, topic.topic)) as helptopic  ,cdata.priority as priority_id, cdata.subject, pri.priority_desc, pri.priority_color  FROM ost_ticket ticket  LEFT JOIN ost_ticket_status status
            ON (status.id = ticket.status_id)  LEFT JOIN ost_user user ON user.id = ticket.user_id LEFT JOIN ost_user_email email ON user.id = email.user_id LEFT JOIN ost_department dept ON ticket.dept_id=dept.dept_id  LEFT JOIN ost_ticket_lock tlock ON (ticket.ticket_id=tlock.ticket_id AND tlock.expire>NOW()
               AND tlock.staff_id!=186)  LEFT JOIN ost_staff staff ON (ticket.staff_id=staff.staff_id)  LEFT JOIN ost_team team ON (ticket.team_id=team.team_id)  LEFT JOIN ost_sla sla ON (ticket.sla_id=sla.id AND sla.isactive=1)  LEFT JOIN ost_help_topic topic ON (ticket.topic_id=topic.topic_id)  LEFT JOIN ost_help_topic ptopic ON (ptopic.topic_id=topic.topic_pid)  LEFT JOIN ost_ticket__cdata cdata ON (cdata.ticket_id = ticket.ticket_id)  LEFT JOIN ost_ticket_priority pri ON (pri.priority_id = cdata.priority)  WHERE (   ( ticket.staff_id=186 AND status.state="open")  OR ticket.dept_id IN (13) ) AND status.state IN (
                'open' )  ORDER BY effective_date DESC LIMIT 0,25]
…


Table 'database.ost_ticket__cdata' doesn't exist<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1146', '[SELECT ticket....')<br />
#1 (root)/include/staff/tickets.inc.php(275): db_query('SELECT ticket.t...')<br />
#2 (root)/scp/tickets.php(519): require_once('/usr/share/ngin...')<br />
#3 {main}
```

I run this query and it returned result. no error. After 30 minutes later, I received another email:

```
[CREATE TABLE `ost_ticket__cdata` (PRIMARY KEY
                (ticket_id)) AS SELECT entry.`object_id` as `ticket_id`, MAX(IF(field.id='20',coalesce(ans.value_id, ans.value),NULL)) as `subject`,MAX(CASE WHEN field.id='22' THEN REPLACE(REPLACE(REPLACE(REPLACE(coalesce(ans.value_id, ans.value), '{', ''), '}', ''), '"', ''), ':', ',') ELSE NULL END) as `priority` FROM ost_form_entry entry
            JOIN ost_form_entry_values ans ON ans.entry_id = entry.id
            JOIN ost_form_field field ON field.id=ans.field_id
            WHERE entry.object_type='T' GROUP BY entry.object_id]

Table 'ost_ticket__cdata' already exists<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1050', '[CREATE TABLE `...')<br />
#1 (root)/include/class.dynamic_forms.php(330): db_query('CREATE TABLE `o...')<br />
#2 (root)/include/class.dynamic_forms.php(315): TicketForm::buildDynamicDataView()<br />
#3 (root)/include/staff/tickets.inc.php(266): TicketForm::ensureDynamicDataView()<br />
#4 (root)/scp/tickets.php(514): require_once('/usr/share/ngin...')<br />
#5 (root)/scp/index.php(17): require('/usr/share/ngin...')<br />
#6 {main}
```

So I think it is runtime error. How to solve this problem? I got almost hundred email everyday.

Thanks

**Comment by infectormp** [comment]
@gtulga why you think this is ostciklet problem? You try install osticket to different server\db?You try exort\import osticket db?

**Comment by mfelber** [comment]
This seems to be duplicate to https://github.com/osTicket/osTicket-1.8/issues/1545

**Comment by kler** [comment]
This issue *may possibly* be fixed by PR #3832

**Comment by leifnel** [comment]
Could be a language issue where the custom fields were not created if not using the default english setup.

https://github.com/osTicket/osTicket/issues/3840

**Comment by hegGK** [comment]
I do have the same/ a similar problem, may be they both have the same reason.
I do get lots of mails like:
[SELECT A1.`id`, A1.`name`, A5.`address` FROM `ost_user` A1 LEFT JOIN `ost_user_email` A2 ON (A1.`id` = A2.`user_id`) LEFT JOIN `ost_organization` A3 ON (A1.`org_id` = A3.`id`) LEFT JOIN `ost_user__cdata` A4 ON (A1.`id` = A4.`user_id`) LEFT JOIN `ost_user_email` A5 ON (A1.`default_email_id` = A5.`id`) WHERE (A2.`address` LIKE '%haus%' OR A1.`name` LIKE '%haus%' OR A3.`name` LIKE '%haus%' OR A4.`phone` LIKE '%haus%') LIMIT 25]

Table 'osticket.ost_user__cdata' doesn't exist<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1146', '[SELECT A1.`id`...')<br />
#1 (root)/include/class.orm.php(3136): db_query('SELECT A1.`id`,...', true, true)<br />
#2 (root)/include/class.orm.php(3192): MySqlExecutor->execute()<br />
#3 (root)/include/class.orm.php(1845): MySqlExecutor->getRow()<br />
#4 (root)/include/class.orm.php(1818): FlatArrayIterator->{closure}()<br />
#5 (root)/include/class.orm.php(1797): CallbackSimpleIterator->next()<br />
#6 (root)/include/class.orm.php(1806): CallbackSimpleIterator->rewind()<br />
#7 (root)/include/class.orm.php(1463): CallbackSimpleIterator->valid()<br />
#8 (root)/include/class.orm.php(1480): CachedResultSet->fillTo(9223372036854775807)<br />
#9 (root)/include/class.orm.php(1489): CachedResultSet->asArray()<br />
#10 (root)/include/ajax.users.php(94): CachedResultSet->getIterator()<br />
#11 (root)/include/class.dispatcher.php(145): UsersAjaxAPI->search()<br />
#12 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('', Array)<br />
#13 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('', Array)<br />
#14 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/users', NULL)<br />
#15 (root)/scp/ajax.php(262): Dispatcher->resolve('/users')<br />
#16 {main}

After I:
* upgraded from the previous version of OSTicket
* the old install used during the upgrade german language files
* even after switching the language back to english after the install those mails keep on coming

For me it seems that during the upgrade due to the german language files in use, some changes where not made. So now the dynamically generated table 'ost_user__cdata' is not created....

Due to exsiting data I do NOT have the option to make a fresh(empty) new install. I have to upgrade the exsiting installation.

Any help is apreciated.

**Comment by Excelspieler** [comment]
It seems as I would have exactly the same problem. Is there any solution nearby?
