### ISSUE TITLE
1.9.11 db error if connection are slow or get error in transition with recent cache browsers

### ISSUE THREAD

**Issue by mckaygerhard** [osTicket/osTicket-1.8#2537]
using the osticket i got this db error when network are slow (under 50Kps or over intense used wifi)

seems its only happened with google chrome i never see when users are under firefox << 27, but with recent firefox and chrome got a lot of those errors.. 

i hear a cache problem under recent google chrome setups and updates of the browser

```
[SELECT ticket.ticket_id,tlock.lock_id,ticket.`number`,ticket.dept_id,ticket.staff_id,ticket.team_id  ,user.name ,email.address as email, dept.dept_name, status.state  ,status.name as status,ticket.source,ticket.isoverdue,ticket.isanswered,ticket.created  ,IF(ticket.duedate IS NULL,IF(sla.id IS NULL, NULL, DATE_ADD(ticket.created, INTERVAL sla.grace_period HOUR)), ticket.duedate) as duedate  ,CAST(GREATEST(IFNULL(ticket.lastmessage, 0), IFNULL(ticket.closed, 0), IFNULL(ticket.reopened, 0), ticket.created) as datetime) as effective_date  ,ticket.created as ticket_created, CONCAT_WS(" ", staff.firstname, staff.lastname) as staff, team.name as team  ,IF(staff.staff_id IS NULL,team.name,CONCAT_WS(" ", staff.lastname, staff.firstname)) as assigned  ,IF(ptopic.topic_pid IS NULL, topic.topic, CONCAT_WS(" / ", ptopic.topic, topic.topic)) as helptopic  ,cdata.priority as priority_id, cdata.subject, pri.priority_desc, pri.priority_color  FROM ost_ticket ticket  LEFT JOIN ost_ticket_status status
            ON (status.id = ticket.status_id)  LEFT JOIN ost_user user ON user.id = ticket.user_id LEFT JOIN ost_user_email email ON user.id = email.user_id LEFT JOIN ost_department dept ON ticket.dept_id=dept.dept_id  LEFT JOIN ost_ticket_lock tlock ON (ticket.ticket_id=tlock.ticket_id AND tlock.expire>NOW()
               AND tlock.staff_id!=3)  LEFT JOIN ost_staff staff ON (ticket.staff_id=staff.staff_id)  LEFT JOIN ost_team team ON (ticket.team_id=team.team_id)  LEFT JOIN ost_sla sla ON (ticket.sla_id=sla.id AND sla.isactive=1)  LEFT JOIN ost_help_topic topic ON (ticket.topic_id=topic.topic_id)  LEFT JOIN ost_help_topic ptopic ON (ptopic.topic_id=topic.topic_pid)  LEFT JOIN ost_ticket__cdata cdata ON (cdata.ticket_id = ticket.ticket_id)  LEFT JOIN ost_ticket_priority pri ON (pri.priority_id = cdata.priority)  WHERE (   ( ticket.staff_id=3 AND status.state="open")  OR ticket.dept_id IN (1,2,3,4,5,6,7,8,9) OR (ticket.team_id IN (2,3,5,6,7, AND status.state="open")  ) AND status.state IN (
                'open' )  ORDER BY effective_date DSC LIMIT 0,40]

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DSC LIMIT 0,40' at line 4<br />
<br />
---- Recular ----<br />
#0 (raíz)/include/mysqli.php(177): osTicket->logDBError('DB Error #1064', '[SELECT ticket....')<br />
#1 (raíz)/include/staff/tickets.inc.php(272): db_query('SELECT ticket.t...')<br />
#2 (raíz)/scp/tickets.php(492): require_once('/var/www/osticket...')<br />
#3 {main}
```

**Comment by ntozier** [comment]
1.9.12 is current.  Please always upgrade to the latest version before reporting issues.  Thank you.

**Comment by mckaygerhard** [comment]
sorry, well i'll upgrade in the weekend and then post feedback here!

**Comment by greezybacon** [comment]
I can't find the text `DSC` anywhere in the project. Did you edit something?

**Comment by mckaygerhard** [comment]
umm i think "DSC" mean descendent order, can see:

```
ORDER BY effective_date DSC LIMIT 0,40
```

and the later see `near 'DSC LIMIT 0,40' at line 4`

umm @greezybacon are u see this notification in mail only, somethings mail presentation changes the body text of presentation

**Comment by ntozier** [comment]
SQL syntax would be DESC.

**Comment by mckaygerhard** [comment]
i dont understand how the "DSC" word get incomplete, i made test now with 1.9.12 and 1.9.11 i cannot reproduce again, the only thing i cannot reproduce its the speed of the wifi when many request are done, seems related to browser so 'ill close concluding that was a problem in chrome (i found many post about currently recent versions of chrome are very buggy)
