### ISSUE TITLE
When adding agents expanded teams, access and permissions are not saved.

### ISSUE THREAD

**Issue by bhiscox** [osTicket/osTicket-1.8#2643]
When adding an agent the only thing saved is the default access level. If I add the user to other roles, teams or additional settings they are not saved.

Once I click save and then add the user's extended access settings and hit save again everything will save properly.

**Comment by infectormp** [comment]
osTicket version?

**Comment by bhiscox** [comment]
Sorry, 1.1.10RC2 

Thank You,
Brady Hiscox

**Comment by devosnw** [comment]
Wanted to say there is definitely a bug here. The problem is the system is trying to save the `StaffDeptAccess` before the `Staff` object get's saved resulting in the `staff_id` column not having a value for that record. The error will look like this:

```
[INSERT INTO `ost_staff_dept_access` SET `dept_id` = '1', `role_id` = '3', `flags` = 1]

Duplicate entry '0-1' for key 'PRIMARY'<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')<br />
#1 (root)/include/class.orm.php(3153): db_query('INSERT INTO `os...', true, true)<br />
#2 (root)/include/class.orm.php(612): MySqlExecutor->execute()<br />
#3 (root)/include/class.staff.php(1114): VerySimpleModel->save()<br />
#4 (root)/include/class.staff.php(1030): Staff->updateAccess(Array, Array)<br />
#5 (root)/scp/staff.php(47): Staff->update(Array, Array)<br />
#6 {main}
```

I've looked around in this code for a bit but can't figure out if the bug happens when [instantiating the new `StaffDeptAccess`](https://github.com/osTicket/osTicket/blob/develop/include/class.staff.php#L1104), [adding the relationship to the `Staff` object](https://github.com/osTicket/osTicket/blob/develop/include/class.staff.php#L1107) or lower level when trying to [save the new `StaffDeptAccess`](https://github.com/osTicket/osTicket/blob/develop/include/class.orm.php#L579) since that `if` statement there looks like it tries to save the parent objects before saving the current object.

For whatever reason, the `$da->staff_id` variable does not have a value. However this will not stop the new staff record from being created successfully. This is why when you update the record it works fine.

**Comment by bertaviader** [comment]
Having the same problem with the version 1.10.4

**Comment by dh3wr** [comment]
Same on v1.12 (a076918)
